theme: jekyll-theme-cayman
title: Qi-Nan Han
description: In-situ fretting fatigue, Nickel-based superalloy, EBSD, Dislocation
# google_analytics: [Your Google Analytics tracking ID]
github: false
show_downloads: false
is_project_page: false
