theme: jekyll-theme-cayman
title: Qi-Nan Han
description: 29 Yudao St., Nanjing 210016, Jiangsu, China | hanqn@nuaa.edu.cn | https://frankhan.net/research/
# In-situ fretting fatigue, Nickel-based superalloy, EBSD, Dislocation
# google_analytics: [Your Google Analytics tracking ID]
github: false
show_downloads: false
is_project_page: false
