theme: jekyll-theme-cayman
title: Qi-Nan Han
description: Fretting fatigue, Nickel-based superalloy, in-situ, EBSD, Dislocation
# google_analytics: [Your Google Analytics tracking ID]
github: false
show_downloads: false
is_project_page: false
